# Generated by Django 6.0.3 on 2026-04-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0006_product_imageurl_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
