# Generated by Django 6.0.3 on 2026-04-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0008_alter_product_image_alter_product_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
